import { isEmptyArray } from "../helpers";
import { NTC_Variants, BFS_Variants, PPI_Variants, RP_Variants, VSH_Variants, SP_Variants } from "./programs";
import { LenderType, ProgramType, BankSize, ResponsivityLevel, DocumentationRequirementLevel, PrepaymentAbilityLevel } from "./programs/types";


export const All_Variants = [...BFS_Variants, ...NTC_Variants, ...PPI_Variants, ...RP_Variants, ...VSH_Variants, ...SP_Variants];

export const checkers = ["targetCustomer", "purpose", "restrictions", "LTV", "mortgage", "FICO", "GDS", "TDS", "bunkrupcy", "population", "squarfeet", "amortization", "term", "intrestRate"];

export function getLenderById(id:string):LenderType|null{
    const results= lenders.filter(lender=>lender.id===id)
    if (isEmptyArray(results)) return null;
        else return results[0];
}
export function getProgramById(id:string):ProgramType|null{
    const results= programs.filter(prog=>prog.id===id)
    if (isEmptyArray(results)) return null;
        else return results[0];
}
 
 export const lenders:LenderType[] = [
     {
         id:"0",
         name:"Lendwise",
         logo:"/imgs/logos/Lendwise.png",
         bunus_products:"",
         approva_benif_portion:1.11,
         color:"#C1DEAE",
         bankSize: BankSize.Small,
         paymentFlexibilityFirstMonth: false,
         paymentFlexibilityMissOne: false,
         onLineBanking: true,
         Heloc: false,
         creditCard: false,
         bundlePricing: false,
         overdraftProtection: false,
         multipleBranch: false,
         responsivity: ResponsivityLevel.Medium,
         hasCashBack: false,
         documentationRequired: DocumentationRequirementLevel.Medium,
         prepaymentAbility: PrepaymentAbilityLevel.High,
     },
     {
         id:"1",
         name:"B2B Bank",
         logo:"/imgs/logos/B2B.svg",
         bunus_products:"",
         approva_benif_portion:0.96,
         color:"#F2F5C8",
         bankSize: BankSize.Big,
         paymentFlexibilityFirstMonth: true,
         paymentFlexibilityMissOne: false,
         onLineBanking: true,
         Heloc: true,
         creditCard: false,
         bundlePricing: true,
         overdraftProtection: true,
         multipleBranch: true,
         responsivity: ResponsivityLevel.Short,
         hasCashBack: false,
         documentationRequired: false,
         prepaymentAbility: PrepaymentAbilityLevel.Medium,
     },
     {
         id:"2",
         name:"CMLS",
         logo:"/imgs/logos/CMLS.svg",
         bunus_products:"",
         approva_benif_portion:1.03,
         color:"#E8E8A6",
         bankSize: BankSize.Big,
         paymentFlexibilityFirstMonth: true,
         paymentFlexibilityMissOne: true,
         onLineBanking: true,
         Heloc: true,
         creditCard: false,
         bundlePricing: false,
         overdraftProtection: false,
         multipleBranch: false,
         responsivity: ResponsivityLevel.Medium,
         hasCashBack: false,
         documentationRequired: DocumentationRequirementLevel.Low,
         prepaymentAbility: PrepaymentAbilityLevel.Medium,
     },
     {
         id:"3",
         name:"Home Trust",
         logo:"/imgs/logos/HomeTrust.png",
         bunus_products:"",
         approva_benif_portion:0.88,
         color:"#96CEB4",
         bankSize: BankSize.Medium,
         paymentFlexibilityFirstMonth: true,
         paymentFlexibilityMissOne: true,
         onLineBanking: true,
         Heloc: false,
         creditCard: true,
         bundlePricing: true,
         overdraftProtection: true,
         multipleBranch: false,
         responsivity: ResponsivityLevel.Long,
         hasCashBack: false,
         documentationRequired: false,
         prepaymentAbility: PrepaymentAbilityLevel.High,
     },
     {
         id:"4",
         name:"Optimum",
         logo:"/imgs/logos/Optimum.svg",
         bunus_products:"",
         approva_benif_portion:0,
         color:"#FF8585",
         bankSize: BankSize.Medium,
         paymentFlexibilityFirstMonth: false,
         paymentFlexibilityMissOne: false,
         onLineBanking: true,
         Heloc: false,
         creditCard: false,
         bundlePricing: false,
         overdraftProtection: false,
         multipleBranch: true,
         responsivity: ResponsivityLevel.Long,
         hasCashBack: false,
         documentationRequired: DocumentationRequirementLevel.Low,
         prepaymentAbility: PrepaymentAbilityLevel.Medium,
     },
     {
         id:"5",
         name:"First National",
         logo:"/imgs/logos/FirstNational.svg",
         bunus_products:"",
         approva_benif_portion:1.03,
         color:"#D9534F",
         bankSize: BankSize.Medium,
         paymentFlexibilityFirstMonth: false,
         paymentFlexibilityMissOne: false,
         onLineBanking: true,
         Heloc: false,
         creditCard: false,
         bundlePricing: false,
         overdraftProtection: false,
         multipleBranch: false,
         responsivity: ResponsivityLevel.Short,
         hasCashBack: false,
         documentationRequired: DocumentationRequirementLevel.Medium,
         prepaymentAbility: PrepaymentAbilityLevel.Medium,
     },
     {
         id:"6",
         name:"Haventree",
         logo:"/imgs/logos/HeavenTree.svg",
         bunus_products:"",
         approva_benif_portion:0,
         color:"#FFAD60",
         bankSize: BankSize.Small,
         paymentFlexibilityFirstMonth: false,
         paymentFlexibilityMissOne: false,
         onLineBanking: true,
         Heloc: false,
         creditCard: false,
         bundlePricing: false,
         overdraftProtection: false,
         multipleBranch: true,
         responsivity: ResponsivityLevel.Short,
         hasCashBack: false,
         documentationRequired: DocumentationRequirementLevel.Low,
         prepaymentAbility: PrepaymentAbilityLevel.High,
     },
     {
         id:"7",
         name:"ICICI Bank",
         logo:"/imgs/logos/ICICI.png",
         bunus_products:"",
         approva_benif_portion:0.91,
         color:"#FFADAD",
         bankSize: BankSize.Small,
         paymentFlexibilityFirstMonth: false,
         paymentFlexibilityMissOne: false,
         onLineBanking: true,
         Heloc: false,
         creditCard: true,
         bundlePricing: false,
         overdraftProtection: true,
         multipleBranch: true,
         responsivity: ResponsivityLevel.Long,
         hasCashBack: false,
         documentationRequired: DocumentationRequirementLevel.Medium,
         prepaymentAbility: PrepaymentAbilityLevel.No,
     },
     {
         id:"8",
         name:"MCAP",
         logo:"/imgs/logos/MCAP.svg",
         bunus_products:"",
         approva_benif_portion:1.23,
         color:"#9D9D9D",
         bankSize: BankSize.Small,
         paymentFlexibilityFirstMonth: false,
         paymentFlexibilityMissOne: false,
         onLineBanking: true,
         Heloc: true,
         creditCard: false,
         bundlePricing: false,
         overdraftProtection: false,
         multipleBranch: false,
         responsivity: ResponsivityLevel.Medium,
         hasCashBack: true,
         documentationRequired: DocumentationRequirementLevel.Medium,
         prepaymentAbility: PrepaymentAbilityLevel.Medium,
     },
     {
         id:"9",
         name:"RFA",
         logo:"/imgs/logos/RFA.svg",
         bunus_products:"",
         approva_benif_portion:1.02,
         color:"#28FFBF",
         bankSize: BankSize.Medium,
         paymentFlexibilityFirstMonth: false,
         paymentFlexibilityMissOne: false,
         onLineBanking: true,
         Heloc: false,
         creditCard: false,
         bundlePricing: false,
         overdraftProtection: false,
         multipleBranch: false,
         responsivity: ResponsivityLevel.Short,
         hasCashBack: false,
         documentationRequired: DocumentationRequirementLevel.Medium,
         prepaymentAbility: PrepaymentAbilityLevel.High,
     },
     {
         id:"10",
         name:"RMG",
         logo:"/imgs/logos/RMG.jpg",
         bunus_products:"",
         approva_benif_portion:1.03,
         color:"#F3C583",
         bankSize: BankSize.Small,
         paymentFlexibilityFirstMonth: false,
         paymentFlexibilityMissOne: false,
         onLineBanking: true,
         Heloc: false,
         creditCard: false,
         bundlePricing: false,
         overdraftProtection: false,
         multipleBranch: false,
         responsivity: ResponsivityLevel.Short,
         hasCashBack: false,
         documentationRequired: DocumentationRequirementLevel.Medium,
         prepaymentAbility: PrepaymentAbilityLevel.Medium,
     },
     {
         id:"11",
         name:"Strive",
         logo:"/imgs/logos/Strive.png",
         bunus_products:"",
         approva_benif_portion:0.98,
         color:"#A0937D",
         bankSize: BankSize.Medium,
         paymentFlexibilityFirstMonth: false,
         paymentFlexibilityMissOne: false,
         onLineBanking: true,
         Heloc: false,
         creditCard: false,
         bundlePricing: false,
         overdraftProtection: false,
         multipleBranch: false,
         responsivity: ResponsivityLevel.Medium,
         hasCashBack: false,
         documentationRequired: DocumentationRequirementLevel.Medium,
         prepaymentAbility: PrepaymentAbilityLevel.No,
     },
     {
         id:"12",
         name:"Scotia",
         logo:"/imgs/logos/Scotia.svg",
         bunus_products:"",
         approva_benif_portion:0.99,
         color:"#FFAEC0",
         bankSize: BankSize.Big,
         paymentFlexibilityFirstMonth: true,
         paymentFlexibilityMissOne: true,
         onLineBanking: true,
         Heloc: true,
         creditCard: true,
         bundlePricing: true,
         overdraftProtection: true,
         multipleBranch: true,
         responsivity: ResponsivityLevel.Short,
         hasCashBack: true,
         documentationRequired: false,
         prepaymentAbility: PrepaymentAbilityLevel.Medium,
     },
     {
         id:"13",
         name:"Merix",
         logo:"/imgs/logos/Merix.png",
         bunus_products:"",
         approva_benif_portion:1.08,
         color:"#98DED9",
         bankSize: BankSize.Medium,
         paymentFlexibilityFirstMonth: false,
         paymentFlexibilityMissOne: false,
         onLineBanking: true,
         Heloc: false,
         creditCard: false,
         bundlePricing: false,
         overdraftProtection: false,
         multipleBranch: false,
         responsivity: ResponsivityLevel.Medium,
         hasCashBack: false,
         documentationRequired: DocumentationRequirementLevel.Medium,
         prepaymentAbility: PrepaymentAbilityLevel.Medium,
     },
     {
         id:"14",
         name:"TD Bank",
         logo:"/imgs/logos/TD.svg",
         bunus_products:"",
         approva_benif_portion:0.98,
         color:"#FDCFDF",
         bankSize: BankSize.Big,
         paymentFlexibilityFirstMonth: true,
         paymentFlexibilityMissOne: true,
         onLineBanking: true,
         Heloc: true,
         creditCard: true,
         bundlePricing: true,
         overdraftProtection: true,
         multipleBranch: true,
         responsivity: ResponsivityLevel.Medium,
         hasCashBack: true,
         documentationRequired: false,
         prepaymentAbility: PrepaymentAbilityLevel.Medium,
     },
 ];
 
 export const programs:ProgramType[] = [
     {
         id:"0",
         name:"Business For Self"
     },
     {
         id:"1",
         name:"New To Canada"
     },
     {
         id:"2",
         name:"Standard Purchase"
     },
     {
         id:"3",
         name:"Rental Property"
     },
     {
         id:"4",
         name:"Purchase Plus Improvement"
     },
     {
         id:"5",
         name:"Vacation - Secondary Home"
     },
 ];
 